# Change these first
owner: Hitesh-Kamero # Your GitHub username
repo: kamero-upptime # The name of this repository

sites:
  - name: Kamero.in Website
    url: https://kamero.in
  - name: Kamero.in Admin
    url: https://login.kamero.in
  - name: Weblink Project
    url: https://kamero.in/anmolkriti
  - name: API v2
    url: https://apiv2.kamero.in/v1/check_app_v2
  - name: Renewal Link
    url: https://event.kamero.in/renew/anmolkriti
  - name: V1 API
    url: https://goapi.kamero.in/v1/event_home_viewer?eventCode=anmolkriti&skip=0&limit=0

status-website:
  # Add your custom domain name
  cname: status.kamero.in
  logoUrl: https://raw.githubusercontent.com/Hitesh-Kamero/kamero-upptime/master/assets/kamero_icon.png
  name: "Kamero status monitor"
  introTitle: "**Kamero Uptime Monitor**"
  introMessage: This portal provides real-time status updates for Kamero.in services and APIs. Kamero - AI powered photo sharing for events.
  navbar:
    - title: Status
      href: /
    - title: Kamero
      href: https://kamero.in
  theme: light
  customCss: /assets/custom-styles.css
  favicon: https://raw.githubusercontent.com/Hitesh-Kamero/kamero-upptime/master/assets/android-chrome-192x192.png
  customHeadHtml: |
    <meta name='description' content='Kamero.in service status'>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap" rel="stylesheet">
  customBodyHtml: |
    <div id="custom-footer" class="footer-content">
      <small>© 2024 Kamero.in. All rights reserved.</small>
    </div>

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Notifications configuration
notifications:
  email:
    - hitesh@kamero.in

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
