# Change these first
owner: kamero-in # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Kamero.in Website
    url: https://kamero.in
  - name: Kamero.in Admin
    url: https://login.kamero.in
  - name: Weblink Project
    url: https://kamero.in/anmolkriti
  - name: API v2
    url: https://apiv2.kamero.in/v1/check_app_v2
  - name: Renewal Link
    url: https://event.kamero.in/renew/anmolkriti
  - name: V1 API
    url: https://goapi.kamero.in/v1/event_home_viewer?eventCode=anmolkriti&skip=0&limit=

status-website:
  # Add your custom domain name
  cname: status.kamero.in
  logoUrl: https://kamero-public.s3.ap-south-1.amazonaws.com/logos/KAMERO+LOGO+COLOUR.png
  name: Kamero.in Status
  introTitle: "**Kamero Uptime Monitor**"
  introMessage: This page provides real-time status updates for Kamero.in services and APIs. Kamero - AI powered photo sharing for events.
  navbar:
    - title: Status
      href: /
    - title: Kamero
      href: https://kamero.in

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

# Notifications configuration
notifications:
  email:
    - hitesh@kamero.in

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
