# Change these first
owner: kamero-in # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Kamero.in Website
    url: https://kamero.in
  - name: Kamero.in Admin
    url: https://login.kamero.in
  - name: Weblink Project
    url: https://kamero.in/anmolkriti
  - name: API v2
    url: https://apiv2.kamero.in/v1/check_app_v2
  - name: Renewal Link
    url: https://event.kamero.in/renew/anmolkriti
  - name: V1 API
    url: https://goapi.kamero.in/v1/event_home_viewer?eventCode=anmolkriti&skip=0&limit=


status-website:
  # Add your custom domain name
  cname: status.kamero.in
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Kamero.in Status
  introTitle: "**Kamero.in Uptime Monitor** is powered by Upptime."
  introMessage: This page provides real-time status updates for Kamero.in services and APIs.
  navbar:
    - title: Status
      href: /
    - title: Kamero
      href: https://kamero.in
      
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "2-59/5 * * * *"

# Notifications configuration
notifications:
  email:
    - hitesh@kamero.in  # Replace with your actual email address

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
